# Generated by Django 3.2.4 on 2021-07-11 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Количество товара')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена')),
                ('in_order', models.BooleanField(default=False, verbose_name='Занятая корзина')),
                ('for_anonymous_users', models.BooleanField(default=False, verbose_name='Для анонимов')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена')),
                ('sale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.GenericIPAddressField(null=True, verbose_name='IP пользователя')),
            ],
            options={
                'verbose_name': 'IP пользователя товара',
                'verbose_name_plural': 'IP пользователя товара',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('rigidity', models.CharField(max_length=50, verbose_name='Жесткость')),
                ('weight', models.BigIntegerField(verbose_name='Масса')),
                ('price', models.DecimalField(decimal_places=2, default=20, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10, verbose_name='Старая цена')),
                ('popularity', models.IntegerField(blank=True, default=1, verbose_name='Популярность')),
                ('quolity', models.IntegerField(blank=True, default=1, verbose_name='Качество')),
                ('description', djrichtextfield.models.RichTextField(blank=True, verbose_name='Описание')),
                ('characters', djrichtextfield.models.RichTextField(blank=True, verbose_name='Характеристики')),
                ('feedbacks', djrichtextfield.models.RichTextField(blank=True, verbose_name='Отзывы')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('image_for_cart', models.ImageField(blank=True, upload_to='', verbose_name='Картинка для корзины')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категории товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('typeof', models.CharField(max_length=8)),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Слайдеры',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя заказчика')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Заказчика')),
                ('agreement', models.BooleanField(default=False, verbose_name='Соглашение с правилами')),
                ('status', models.CharField(choices=[('Новый заказ', 'Новый заказ'), ('В процессе', 'Заказ в обработке'), ('Готов', 'Заказ готов'), ('Завершен', 'Заказ выполнен')], default='Новый заказ', max_length=100, verbose_name='Статус заказ')),
                ('buying_type', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=100, verbose_name='Тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения заказа')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to='main.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='main.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Goods_Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='main.good')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размер товара',
            },
        ),
        migrations.CreateModel(
            name='Goods_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='main.good')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинка товара',
            },
        ),
        migrations.CreateModel(
            name='Goods_Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.ImageField(blank=True, upload_to='', verbose_name='Иконки')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Icons', to='main.good')),
            ],
            options={
                'verbose_name': 'Иконка товара',
                'verbose_name_plural': 'Товара товара',
            },
        ),
        migrations.CreateModel(
            name='Goods_Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.BigIntegerField(blank=True, default=20, verbose_name='Высота')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Height', to='main.good')),
            ],
            options={
                'verbose_name': 'Высота товара',
                'verbose_name_plural': 'Высота товара',
            },
        ),
        migrations.CreateModel(
            name='Goods_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='ID объекта')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10, verbose_name='Итоговая цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10, verbose_name='Старая цена')),
                ('sale', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10, verbose_name='Скидка')),
                ('height', models.IntegerField(blank=True, default=0, null=True, verbose_name='Высота')),
                ('size', models.CharField(blank=True, default='Не заполнено', max_length=50, verbose_name='Размер')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='main.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип содержимого')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина товара',
                'verbose_name_plural': 'Корзина товара',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.goodscategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='main.Order', verbose_name='Заказы покупателя'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='main.Goods_Cart', verbose_name='Товары'),
        ),
        migrations.CreateModel(
            name='Goods_Cart_Proxy',
            fields=[
            ],
            options={
                'verbose_name': 'Сводная таблица товара',
                'verbose_name_plural': 'Сводная таблица товара',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.goods_cart',),
        ),
    ]
